# Site settings
title: "DDEEE"
description: "Dopamine-driven Electrical and Electronic Engineering by Yousei Ushida"
baseurl: "" # サブディレクトリがある場合のみ設定（GitHub Pagesメインサイトなら空文字）
url: "https://youseiushida.github.io" # GitHub Pagesの場合

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima # GitHub Pages標準テーマ

# Kramdown settings (数式対応)
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false

# MathJax設定（数式表示用）
mathjax: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections（任意：プロジェクト紹介など）
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Include files
include:
  - _pages

# Timezone
timezone: Asia/Tokyo

# Encoding
encoding: utf-8

# Repository (GitHub連携用)
repository: youseiushida/youseiushida.github.io

# GitHub Pages specific
github: [metadata]

# Social links
social_links:
  github: youseiushida